Separate POSIX and Windows build/test into stages
dotnet/coreclr pull request #26739
Opened 2019-09-16 22:38 UTC by lpereira

This allows builds that complete faster to start testing rather than waiting for all builds to finish before executing the testing jobs.

(Leaving the PR as draft until this is tested; this is my first time using Azure Pipelines.)

2019-09-26 23:51 UTC, lpereira commented
/azp run coreclr-ci

2019-10-08 00:12 UTC, lpereira commented on eng/gen-pr-yaml.py
> +#!/usr/bin/python3
I talked with @jashook the other day, and we reached the same conclusion.  I'm busy with other things at the moment but I'll ditch the generator.

2019-10-15 21:47 UTC, lpereira commented
Rebased and re-pushed the YML file without the script.  Added some comments so it's roughly similar to the previous version in that regard.  There are is some work to do here, mostly to make better use of the `platforms` list, but couldn't unfortunately make it work the way I wanted with the time I had to work on this.  Regardless, this is doing what we wanted: it's still checking out only once per group of platforms (unix/windows), and concurrent stages are executed to build/test, per platform.
I'll probably make changes to the `internal.yml` file so it looks more like this one, to aid in the maintenance process (which was the main the point in this refactor anyway).
Things should be cleaned up after that, too.  I just need to carve some time to work on these things.

2019-10-28 16:30 UTC, jashook requested changes
It looks to me like the change is doing a few strange things. First, there are now two `build_linux_arm_checked` jobs. One is a (test) build that is being created erroneously. Second, it seems like this change regresses the re-use of manged test components built on OSX. Although it still looks like publishing is happening.

2019-10-28 16:30 UTC, jashook commented on eng/pipelines/pr.yml
> +  displayName: Linux arm checked (build)
I think it is best to remove (build|test) from the individual job names. It duplicates information in the job display.

2019-10-28 16:30 UTC, jashook commented on eng/pipelines/pr.yml
> +  displayName: Checkout (unix)
Nit: can we change the name to `Checkout - Unix` and `Checkout - Windows` now that stages include (build). To keep things similar.

2019-11-06 21:04 UTC, maryamariyan commented
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

2019-12-02 19:37 UTC, maryamariyan commented
Thank you for your contribution. As announced in #27549 the dotnet/runtime repository will be used going forward for changes to this code base. Closing this PR as no more changes will be accepted into master for this repository. If you’d like to continue working on this change please move it to dotnet/runtime.

2019-12-02 19:37 UTC, closed without merging