WIP: [arm64] CoreCLR Implement more SIMD intrinsics
dotnet/coreclr pull request #26769
Opened 2019-09-18 17:38 UTC by TamarChristinaArm

This is a WIP for adding more AArch64 SIMD and Scalar intrinsics.

The tbl and tbx assembly are not yet correct as I haven't looked further into
how to handle the register lists.

I am in the process of refactoring the testsuite so that doesn't compile yet either.

This adds the following intrinsics

- ReverseBitOrder
- AbsoluteCompareGreatherThanOrEqual
- AbsoluteCompareGreatherThan
- LeftShiftAndInsert
- RightShiftAndInsert
- ExtractAndNarrowLow
- ExtractAndNarrowHigh
- UnzipEven
- UnzipOdd
- ZipLow
- ZipHigh
- TableVectorLookup
- TableVectorLookupExtension
- TransposeVectorOdd
- TransposeVectorEven
- MultiplyAndSubtract
- MultiplyAndAdd
- AddAcross

2019-09-18 17:38 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/coreclr?pullRequest=26769) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/coreclr?pullRequest=26769) before we can accept your contribution.<br/><br/>:x: TamarChristinaArm [sign now](https://cla.dotnetfoundation.org/dotnet/coreclr?pullRequest=26769)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/coreclr?pullRequest=26769) it.</sub>

2019-09-18 17:42 UTC, BruceForstall commented
cc @echesakovMSFT @CarolEidt @tannergooding

2019-09-23 22:15 UTC, briansull requested changes

2019-09-23 22:15 UTC, briansull commented on src/jit/emitarm64.cpp
> +        case IF_DV_1D: // DV_1D   .Q.........mmmmm .ll...nnnnnddddd      Vd,{ V... },Vm   (tbl - structure load store)
The naming convention used for instruction formats require this to be named starting with DV_3 as it encodes three registers

2019-09-25 23:43 UTC, erozenfeld commented
@dotnet/jit-contrib

2019-10-02 22:35 UTC, BruceForstall commented
@TamarChristinaArm Can you give us an idea of your plan for getting these finished and checked in?

My expectation is that you will:

1. Wait for https://github.com/dotnet/coreclr/pull/25508 to be merged,
2. Rebase on top of that,
3. Get everything passing,
4. Get it reviewed and merged.

I presume you will get the currently proposed set of intrinsics implemented here merged before starting on additional ones.

Does that match your plan?

2019-10-03 14:28 UTC, TamarChristinaArm commented
@BruceForstall 

My plan is

1. Make the required CoreFX changes (early next week)
2. Split off the already accepted Intrinsics to a different patch
3. Submit proposals for the rest
4. Write minimal tests since @tannergooding  is changing the testing framework
5. Push the two PRs

At that point I will leave it up to you guys to decide if you want to wait till #25508 has been accepted or are happy to go ahead.
Either works for me.

I am working on sorting being able to contribute to CoreFX but in the mean time will make the changes so I can test these intrinsics.

2019-10-03 14:53 UTC, tannergooding commented
I believe it will be easiest to just wait for #25508 to be merged. The S.P.Corelib changes have already been done (hence the new merge conflicts in this PR) and are now merged on the CoreFX side, so #25508 should become unblocked today.

The remaining work on #25508 is to add support for loading vectors from memory and then writing the basic tests.

2019-10-07 12:08 UTC, TamarChristinaArm commented
Ah ok, I'll rebase this one than and get started on getting these in. Thanks!

2019-11-06 21:04 UTC, maryamariyan commented
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

2019-12-02 19:37 UTC, maryamariyan commented
Thank you for your contribution. As announced in #27549 the dotnet/runtime repository will be used going forward for changes to this code base. Closing this PR as no more changes will be accepted into master for this repository. If you’d like to continue working on this change please move it to dotnet/runtime.

2019-12-02 19:37 UTC, closed without merging