Backports Fix build on Alpine edge dotnet/runtime#45352
dotnet/coreclr pull request #28226
Opened 2021-12-17 01:50 UTC by ayakael

For Alpine Linux dotnet31 packaging project, see dotnet/source-build#2685

2022-01-03 13:46 UTC, janvorli approved these changes
LGTM, thank you!

2022-01-11 18:52 UTC, hoyosjs approved these changes

2022-01-11 18:56 UTC, hoyosjs requested changes
This was already in 3.1 branch with this commit: https://github.com/dotnet/coreclr/commit/fd5f28af2560df0cbeed9b76c022b61457a2fe57

2022-01-13 19:34 UTC, ayakael commented
Quite right! Sorry for missing that, I had backported these changes for the Alpine packaging projet last August via a patch, and didn't see that new version of dotnet-3.1 backported these changes last release. Closing pull request.

2022-01-13 19:34 UTC, closed without merging